name: Rust CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6

      - name: Install Python Packages
        run: |
          uv venv
          uv pip install -r ./scripts/requirements.txt

      # rust-cache very carefully caches toolchains and target directories,
      # based on the job and toolchain and other factors. See
      # https://github.com/Swatinem/rust-cache#cache-details for what gets
      # cached, what gets used as part of the key, and what additional handling
      # happens to make the cache reliable and smaller.
      - uses: Swatinem/rust-cache@v2

      # Run after `rust-cache` so that this is cached.
      - run: rustup update

      - name: Check formatting
        run: |
          export RUSTFLAGS="-D warnings"
          export RUSTDOCFLAGS="-D warnings"
          cargo fmt --check

      - name: Provision Dev Package
        run: |
          sudo apt update && sudo apt install -y cmake

      - name: LLVM Install
        uses: ZhongRuoyu/setup-llvm@v0.1.1
        with:
          llvm-version: 21

      - name: Compile release
        run: cargo build --release

      - name: Run tests
        run: cargo test --release

      - name: Run testsuite
        run: uv run scripts/test_translator.py tests